### ISSUE TITLE
UnhandledPromiseRejectionWarning when using linear-gradient CSS that has been passed through cssnano

### ISSUE THREAD

**Issue by philwolstenholme** [mistakster/postcss-alter-color#3]
When trying to use the plugin on some CSS containing gradients that have been passed through cssnano's [minifyGradients](https://cssnano.co/optimisations/minifygradients/) function (this function is enabled by default in cssnano), the plugin fails with the error below:

```
UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
at /path/to/my/css/dist/style.css:1:42685
at /path/to/my/css/dist/style.css:1:42836
at nodeColor.every (/path/to/my/css/node_modules/postcss-alter-color/lib/visitors/function.js:16:80)
at Array.every (<anonymous>)
at compareColors (/path/to/my/css/node_modules/postcss-alter-color/lib/visitors/function.js:15:6)
at Object.<anonymous> (/path/to/my/css/node_modules/postcss-alter-color/lib/visitors/function.js:39:9)
at Object.<anonymous> (/path/to/my/css/node_modules/css-tree/lib/walker/create.js:13:16)
at List.walkNode (/path/to/my/css/node_modules/css-tree/lib/walker/create.js:155:19)
at List.each (/path/to/my/css/node_modules/css-tree/lib/utils/list.js:159:12)
at Object.eval [as Value] (eval at createTypeIterator (/path/to/my/css/node_modules/css-tree/lib/walker/create.js:112:12), <anonymous>:3:15)
at walkNode (/path/to/my/css/node_modules/css-tree/lib/walker/create.js:158:37)
at Object.walk (/path/to/my/css/node_modules/css-tree/lib/walker/create.js:214:9)
```

The  below code can be used to demonstrate the error.

`.i-dont-work` and `.i-dont-work-either` cause the error as they are missing some stop positions for the gradient (cssnano has removed these as they are unnecessary, and the CSS is still valid without them).

If we add in the stop positions (see `.i-work-now` and `.i-work-now-too`) then the error goes away.

```css
.i-work {
  background-image: linear-gradient(180deg, rgba(0, 0, 0, 0.5), transparent);
}

.i-dont-work {
  background-image: linear-gradient(180deg, transparent 0, transparent);
}

.i-dont-work-either {
  background-image: linear-gradient(90deg, #009ac1, #42d9ff 37.5%, #009ac1 75%);
}

/* Add in the missing digits */

.i-work-now {
  background-image: linear-gradient(180deg, transparent 0, transparent 0);
}

.i-work-now-too {
  background-image: linear-gradient(
    90deg,
    #009ac1 0,
    #42d9ff 37.5%,
    #009ac1 75%
  );
}
```
